### ISSUE TITLE
Does not work after upgrading Simarine

### ISSUE THREAD

**Issue by anderhau2** [htool/Pico2SignalK#8]
As we have talked about on email. I have now tried a brand new Simarine Unit, and a new RPI with clean installed Open Plotter. It will not communicate. Log looks like this:

Aug 19 20:31:27 2024-08-19T19:31:27.815Z pico2signalk Starting plugin
Aug 19 20:31:28 2024-08-19T19:31:28.168Z pico2signalk Error: Error: bind EADDRINUSE 0.0.0.0:43210
Aug 19 20:31:28 signalk-server running at 0.0.0.0:[object Object]
Aug 19 20:31:28 2024-08-19T19:31:28.418Z pico2signalk sensorList: {"0":{"type":10,"pos":0},"1":{"type":7,"pos":1},"2":{"type":4,"pos":2},"3":{"type":"null","pos":3},"4":{"type":"null","pos":3},"5":{"name":"Barometer","type":"barometer","pos":3},"6":{"name":"PICO INTERNAL","type":"volt","pos":5},"7":{"type":"null","pos":11},"8":{"type":"null","pos":11},"9":{"type":"null","pos":11},"10":{"name":"12V BANK #1","type":"current","pos":11},"11":{"name":"SC503 [2575] 1","type":"volt","pos":13},"12":{"name":"SC503 [2575] 2","type":"volt","pos":14},"13":{"name":"SC503 [2575] 1","type":"ohm","pos":15},"14":{"name":"SC503 [2575] 2","type":"ohm","pos":16},"15":{"name":"SC503 [2575] 3","type":"ohm","pos":17},"16":{"name":"24V TEKNISK","type":"current","pos":18},"17":{"name":"SC503 [0862] 1","type":"volt","pos":20},"18":{"name":"SC503 [0862] 2","type":"volt","pos":21},"19":{"name":"SC503 [0862] 1","type":"ohm","pos":22},"20":{"name":"SC503 [0862] 2","type":"ohm","pos":23},"21":{"name":"SC503 [0862] 3","type":"ohm","pos":24},"22":{"name":"ST107 [7161] 1","type":"volt","pos":25},"23":{"name":"ST107 [7161] 2","type":"volt","pos":26},"24":{"name":"ST107 [7161] 3","type":"volt","pos":27},"25":{"name":"ST107 [7161] 1","type":"ohm","pos":28},"26":{"name":"ST107 [7161] 2","type":"ohm","pos":29},"27":{"name":"ST107 [7161] 3","type":"ohm","pos":30},"28":{"name":"ST107 [7161] 4","type":"ohm","pos":31},"29":{"type":"XX","pos":32},"30":{"type":20,"pos":33},"31":{"name":"12-24v Omformer","type":"current","pos":34},"32":{"name":"Ledig (var sol) ","type":"current","pos":36},"33":{"name":"Kj?ling","type":"current","pos":38},"34":{"name":"Smarthus","type":"current","pos":40},"35":{"name":"SCQ25T [5416] 1","type":"volt","pos":42},"36":{"name":"SCQ25T [5416] 2","type":"volt","pos":43},"37":{"name":"SCQ25T [5416] 3","type":"volt","pos":44},"38":{"name":"SCQ25T [5416] 1","type":"ohm","pos":45},"39":{"name":"SCQ25T [5416] 2","type":"ohm","pos":46},"40":{"name":"SCQ25T [5416] 3","type":"ohm","pos":47},"41":{"name":"SCQ25T [5416] 4","type":"ohm","pos":48},"42":{"type":"XX","pos":49},"43":{"name":"Webasto Luftvarmer 24v","type":"current","pos":50},"44":{"name":"Solceller Bak","type":"current","pos":52},"45":{"name":"230v Inverter","type":"current","pos":54},"46":{"name":"Solceller Dekk","type":"current","pos":56},"47":{"type":"XX","pos":58},"48":{"name":"12V BANK #1","capacity.nominal":17280000,"type":"battery","pos":59},"49":{"name":"24V TEKNISK","capacity.nominal":7776000,"type":"battery","pos":64},"50":{"name":"DIESEL BB","capacity":1000,"fluid_type":"diesel","fluid":"fuel","type":"tank","pos":69},"51":{"name":"VANN","capacity":1000,"fluid_type":"fresh water","fluid":"freshWater","type":"tank","pos":70},"52":{"name":"DIESEL SB","capacity":1000,"fluid_type":"diesel","fluid":"fuel","type":"tank","pos":71},"53":{"name":"SEPTIK BAK ","capacity":250,"fluid_type":"blackwater","fluid":"wasteWater","type":"tank","pos":72},"54":{"name":"Vann Batterirom","capacity":100,"fluid_type":"blackwater","fluid":"wasteWater","type":"tank","pos":73},"55":{"name":"BATTERY 3","capacity.nominal":4320000,"type":"battery","pos":74}}

**Comment by htool** [comment]
What does 'ip addr show' give as a result?

**Comment by anderhau2** [comment]
pi@openplotter:~ $ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 2c:cf:67:75:22:84 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.128/24 brd 192.168.1.255 scope global dynamic noprefixroute eth0
       valid_lft 76472sec preferred_lft 76472sec
    inet6 fd7f:7f99:86a6:aadd:d1b2:504:6652:29ae/64 scope global dynamic noprefixroute
       valid_lft 1773sec preferred_lft 1773sec
    inet6 fe80::fdf1:e643:759b:cecb/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 2c:cf:67:75:22:85 brd ff:ff:ff:ff:ff:ff
4: wlan9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 2e:cf:67:d5:22:85 brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.1/24 brd 10.42.0.255 scope global noprefixroute wlan9
       valid_lft forever preferred_lft forever
    inet6 fe80::2ccf:67ff:fed5:2285/64 scope link
       valid_lft forever preferred_lft forever

**Comment by anderhau2** [comment]
As mentioned by email, I get the same "Error: Error: bind EADDRINUSE" if I turn the Simarine unit completely off (cut power). This is from a brand new RPI 5.0, installed with clean Open Plotter Image with no other software installed. I'm wondering if the EADDRINUSE error is unrelated to the fact that data is not coming from Simarine. It could have been there before without me seeing it.

I'm able to use teamviewer onto my PC in the boat, and from there remote into RPI either by VNC or SSH. You are welcome to debug on my install if you want. I'm also able to cut power to Simarine remotely, but not much other changes to Simarine setup.

**Comment by htool** [comment]
the error is about a port already in use for listening, which means either another process already opened it, or the same device is already in listening mode.

The config reads well, so that's ok.

On the network Pico sends out UDP broadcast data, which needs to be seen by the RPi.
tcpdump is the command to verify as well as enabling debug for the plugin.

If network traffic is reaching the Rpi, and the plugin can see it, maybe it fails one of the sanity checks.

What does plugin debug output look like again?

**Comment by htool** [comment]
uncomment line 80:
      // app.debug(message)

and add:
 app.debug("Length: %d", message.length)

**Comment by anderhau2** [comment]
> uncomment line 80: // app.debug(message)
> 
> and add: app.debug("Length: %d", message.length)

What file is this, and location? 😊

**Comment by anderhau2** [comment]
Any chance of just make an appointment for a workshop where I let you onto the RPI remotely? I guess it would be far more efficient then me being in the middle... 😊

**Comment by itemir** [comment]
I am now having a similar problem, oddly enough this was working before. Pretty certain there is nothing else listening on the same port, this happens on a Raspberry Pi also on a Victron/Venus OS running Signal K:

```
Jun 14 09:20:59 2025-06-14T16:20:59.104Z pico2signalk Starting plugin
Jun 14 09:20:59 [object Object]
Jun 14 09:20:59 2025-06-14T16:20:59.582Z pico2signalk Error: Error: bind EADDRINUSE 0.0.0.0:43210
Jun 14 09:20:59 signalk-server running at 0.0.0.0:[object Object]
Jun 14 09:20:59 ws connection connected to venus.local:3000
Jun 14 09:21:00 2025-06-14T16:21:00.089Z pico2signalk sensorList: {"0":{"type":10,"pos":0},"1":{"type":7,"pos":1},"2":{"type":4,"pos":2},"3":{"type":"null","pos":3},"4":{"type":"null","pos":3},"5":{"name":"Barometer","type":"barometer","pos":3},"6":{"name":"PICO INTERNAL","type":"volt","pos":5},"7":{"type":"null","pos":11},"8":{"type":"null","pos":11},"9":{"type":"null","pos":11},"10":{"name":"ST107 [6254] U1","type":"volt","pos":11},"11":{"name":"ST107 [6254] U2","type":"volt","pos":12},"12":{"name":"ST107 [6254] U3","type":"volt","pos":13},"13":{"name":"ST107 [6254] R1","type":"ohm","pos":14},"14":{"name":"ST107 [6254] R2","type":"ohm","pos":15},"15":{"name":"ST107 [6254] R3","type":"ohm","pos":16},"16":{"name":"ST107 [6254] R4","type":"ohm","pos":17},"17":{"type":"XX","pos":18},"18":{"name":"Starboard Water Tank","capacity":110,"fluid_type":"fresh water","fluid":"freshWater","type":"tank","pos":19},"19":{"name":"Holding Tank","capacity":100,"fluid_type":"blackwater","fluid":"wasteWater","type":"tank","pos":20},"20":{"name":"Bow Water Tank (Aft)","capacity":150,"fluid_type":"fresh water","fluid":"freshWater","type":"tank","pos":21},"21":{"name":"Main Fuel Tank","capacity":155,"fluid_type":"diesel","fluid":"fuel","type":"tank","pos":22}}
```

Traffic is received on port 43210

```
root@RenaissancePi:~# tcpdump -i eth0 port 43210
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
09:24:19.692311 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:19.790567 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:19.892826 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:19.990561 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:20.088528 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 1156
09:24:20.097220 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:20.191917 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:20.292267 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:20.390514 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:20.490521 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:20.591148 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:20.691056 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:20.791887 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:20.897334 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:20.990533 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:21.093402 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 1156
09:24:21.100495 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:21.191604 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:21.287632 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:21.390603 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
09:24:21.492282 IP 192.168.50.86.43210 > 192.168.50.255.43210: UDP, length 156
```

**Comment by anderhau2** [comment]
This issue was never resolved and it eventuallly made me replace the complete Simarine system. I could not rely on something this fragile. Now I have Victron and Cerbo that work flawless.

**Comment by itemir** [comment]
Yes, this is definitely finicky. Changing the sensors to Cerbo is not an option for me right now but I also don't think it is about the Simarine itself, it is sending data as expected. @htool any thoughts? Happy to do more troubleshooting.

**Comment by itemir** [comment]
Ok, made some progress here. @htool I enabled additional debugging as you suggested earlier and found the reason of `Error: bind EADDRINUSE 0.0.0.0:43210` error. It seems to be because `pico.py` runs almost simultaneously with socket bind. Adding a delay to socket bind solved this. Here are the changes I made in `index.js`

Additional debugging at line 80:

```
      app.debug(message)
      app.debug("Length: %d", message.length)
```

Commented out more debugging in 85-86:

```
  app.debug("sensorList[" + str(item) + "]: " + sensorList[item]["name"])
```

And wrapped socket bind in a setTimeout so it starts with 5 seconds delay

```
    // Do a delayed start to prevent address in use error
    setTimeout (function () {
      app.debug('Binding to port');
      socket.bind(port, function() {
        socket.setBroadcast(true);
        const address = socket.address()
        app.debug("Client using port " + address.port)
      })
    }, 5000);
```

With this EADDRINUSE disappears and we start getting more data but it doesn't seem to get parsed:

```
Jun 14 09:52:10 2025-06-14T16:52:10.271Z pico2signalk Starting plugin
Jun 14 09:52:10 [object Object]
Jun 14 09:52:10 signalk-server running at 0.0.0.0:[object Object]
Jun 14 09:52:11 ws connection connected to venus.local:3000
Jun 14 09:52:11 2025-06-14T16:52:11.601Z pico2signalk sensorList: {"0":{"type":10,"pos":0},"1":{"type":7,"pos":1},"2":{"type":4,"pos":2},"3":{"type":"null","pos":3},"4":{"type":"null","pos":3},"5":{"name":"Barometer","type":"barometer","pos":3},"6":{"name":"PICO INTERNAL","type":"volt","pos":5},"7":{"type":"null","pos":11},"8":{"type":"null","pos":11},"9":{"type":"null","pos":11},"10":{"name":"ST107 [6254] U1","type":"volt","pos":11},"11":{"name":"ST107 [6254] U2","type":"volt","pos":12},"12":{"name":"ST107 [6254] U3","type":"volt","pos":13},"13":{"name":"ST107 [6254] R1","type":"ohm","pos":14},"14":{"name":"ST107 [6254] R2","type":"ohm","pos":15},"15":{"name":"ST107 [6254] R3","type":"ohm","pos":16},"16":{"name":"ST107 [6254] R4","type":"ohm","pos":17},"17":{"type":"XX","pos":18},"18":{"name":"Starboard Water Tank","capacity":110,"fluid_type":"fresh water","fluid":"freshWater","type":"tank","pos":19},"19":{"name":"Holding Tank","capacity":100,"fluid_type":"blackwater","fluid":"wasteWater","type":"tank","pos":20},"20":{"name":"Bow Water Tank (Aft)","capacity":150,"fluid_type":"fresh water","fluid":"freshWater","type":"tank","pos":21},"21":{"name":"Main Fuel Tank","capacity":155,"fluid_type":"diesel","fluid":"fuel","type":"tank","pos":22}}
Jun 14 09:52:15 2025-06-14T16:52:15.292Z pico2signalk Binding to port
Jun 14 09:52:15 2025-06-14T16:52:15.294Z pico2signalk listening on :0.0.0.0:43210
Jun 14 09:52:15 2025-06-14T16:52:15.295Z pico2signalk Client using port 43210
Jun 14 09:52:15 2025-06-14T16:52:15.342Z pico2signalk 0000000000ffb002817896008fff0001684da979ff0101684d46d7ff0201fffffc16ff030100018f1dff040100000009ff050100006610ff0901610fff1aff0a01fffffc16ff0b0100000530ff0c0100000000ff0d0100000000ff0e01000000b1ff0f010000ffffff1001000000ccff11010000001dff120100000000ff130103e8044cff140102cf02cfff150100b4010fff160103e8060effcca3
Jun 14 09:52:15 2025-06-14T16:52:15.344Z pico2signalk Length: 312
Jun 14 09:52:15 ReferenceError: str is not defined at /home/itemir/.signalk/node_modules/pico2signalk/index.js:86:14 at Array.forEach (<anonymous>) at Socket.<anonymous> (/home/itemir/.signalk/node_modules/pico2signalk/index.js:85:33) at Socket.emit (node:events:518:28) at UDP.onMessage [as onmessage] (node:dgram:988:8)
Jun 14 09:52:16 2025-06-14T16:52:16.353Z pico2signalk 0000000000ffb002817896008fff0001684da97aff0101684d46d7ff0201fffffc16ff030100018f1dff040100000009ff050100006614ff0901610fff1aff0a01fffffc16ff0b010000053fff0c0100000000ff0d0100000000ff0e01000000b1ff0f010000ffffff1001000000cdff11010000001dff120100000000ff130103e8044cff140102cf02cfff150100b4010fff160103e8060eff97c2
Jun 14 09:52:16 2025-06-14T16:52:16.359Z pico2signalk Length: 312
Jun 14 09:52:16 ReferenceError: str is not defined at /home/itemir/.signalk/node_modules/pico2signalk/index.js:86:14 at Array.forEach (<anonymous>) at Socket.<anonymous> (/home/itemir/.signalk/node_modules/pico2signalk/index.js:85:33) at Socket.emit (node:events:518:28) at UDP.onMessage [as onmessage] (node:dgram:988:8)
Jun 14 09:52:17 2025-06-14T16:52:17.368Z pico2signalk 0000000000ffb002817896008fff0001684da97bff0101684d46d7ff0201fffffc16ff030100018f1dff040100000009ff05010000660eff0901610fff1aff0a01fffffc16ff0b01000004f0ff0c0100000000ff0d0100000000ff0e01000000b1ff0f010000ffffff1001000000ccff11010000001dff120100000000ff130103e8044cff140102cf02cfff150100b4010fff160103e8060eff86ad
Jun 14 09:52:17 2025-06-14T16:52:17.369Z pico2signalk Length: 312
Jun 14 09:52:17 ReferenceError: str is not defined at /home/itemir/.signalk/node_modules/pico2signalk/index.js:86:14 at Array.forEach (<anonymous>) at Socket.<anonymous> (/home/itemir/.signalk/node_modules/pico2signalk/index.js:85:33) at Socket.emit (node:events:518:28) at UDP.onMessage [as onmessage] (node:dgram:988:8)
Jun 14 09:52:18 2025-06-14T16:52:18.444Z pico2signalk 0000000000ffb002817896008fff0001684da97cff0101684d46d7ff0201fffffc16ff030100018f1cff040100000009ff05010000660aff0901610fff1aff0a01fffffc16ff0b010000053dff0c0100000000ff0d0100000000ff0e01000000b1ff0f010000ffffff1001000000ccff11010000001dff120100000000ff130103e8044cff140102cf02cfff150100b4010fff160103e8060eff413d
Jun 14 09:52:18 2025-06-14T16:52:18.445Z pico2signalk Length: 312
Jun 14 09:52:18 ReferenceError: str is not defined at /home/itemir/.signalk/node_modules/pico2signalk/index.js:86:14 at Array.forEach (<anonymous>) at Socket.<anonymous> (/home/itemir/.signalk/node_modules/pico2signalk/index.js:85:33) at Socket.emit (node:events:518:28) at UDP.onMessage [as onmessage] (node:dgram:988:8)
Jun 14 09:52:19 2025-06-14T16:52:19.444Z pico2signalk 0000000000ffb002817896008fff0001684da97dff0101684d46d7ff0201fffffc16ff030100018f1cff040100000009ff050100006603ff0901610fff1aff0a01fffffc16ff0b0100000542ff0c0100000000ff0d0100000000ff0e01000000b0ff0f010000ffffff1001000000cdff11010000001dff120100000000ff130103e8044cff140102ce02ceff150100b4010fff160103e8060efffda3
Jun 14 09:52:19 2025-06-14T16:52:19.445Z pico2signalk Length: 312
Jun 14 09:52:19 ReferenceError: str is not defined at /home/itemir/.signalk/node_modules/pico2signalk/index.js:86:14 at Array.forEach (<anonymous>) at Socket.<anonymous> (/home/itemir/.signalk/node_modules/pico2signalk/index.js:85:33) at Socket.emit (node:events:518:28) at UDP.onMessage [as onmessage] (node:dgram:988:8)
Jun 14 09:52:20 2025-06-14T16:52:20.444Z pico2signalk 0000000000ffb002817896008fff0001684da97eff0101684d46d7ff0201fffffc16ff030100018f1cff040100000009ff05010000660bff0901610fff1aff0a01fffffc16ff0b0100000537ff0c0100000000ff0d0100000000ff0e01000000b0ff0f010000ffffff1001000000ccff11010000001dff120100000000ff130103e8044cff140102ce02ceff150100b4010fff160103e8060eff8fae
Jun 14 09:52:20 2025-06-14T16:52:20.445Z pico2signalk Length: 312
Jun 14 09:52:20 ReferenceError: str is not defined at /home/itemir/.signalk/node_modules/pico2signalk/index.js:86:14 at Array.forEach (<anonymous>) at Socket.<anonymous> (/home/itemir/.signalk/node_modules/pico2signalk/index.js:85:33) at Socket.emit (node:events:518:28) at UDP.onMessage [as onmessage] (node:dgram:988:8)
Jun 14 09:52:21 2025-06-14T16:52:21.540Z pico2signalk 0000000000ffb002817896008fff0001684da97fff0101684d46d7ff0201fffffc16ff030100018f1cff040100000009ff050100006612ff0901610fff1aff0a01fffffc16ff0b010000054eff0c0100000000ff0d0100000000ff0e01000000b1ff0f010000ffffff1001000000cdff11010000001dff120100000000ff130103e8044cff140102cf02cfff150100b50110ff160103e8060effeab4
Jun 14 09:52:21 2025-06-14T16:52:21.541Z pico2signalk Length: 312
Jun 14 09:52:21 ReferenceError: str is not defined at /home/itemir/.signalk/node_modules/pico2signalk/index.js:86:14 at Array.forEach (<anonymous>) at Socket.<anonymous> (/home/itemir/.signalk/node_modules/pico2signalk/index.js:85:33) at Socket.emit (node:events:518:28) at UDP.onMessage [as onmessage] (node:dgram:988:8)
Jun 14 09:52:22 2025-06-14T16:52:22.541Z pico2signalk 0000000000ffb002817896008fff0001684da980ff0101684d46d7ff0201fffffc16ff030100018f1cff040100000009ff05010000660fff0901610fff1aff0a01fffffc16ff0b01000004efff0c0100000000ff0d0100000000ff0e01000000b1ff0f010000ffffff1001000000ccff11010000001dff120100000000ff130103e8044cff140102cf02cfff150100b50110ff160103e8060effa7ba
Jun 14 09:52:22 2025-06-14T16:52:22.542Z pico2signalk Length: 312
Jun 14 09:52:22 ReferenceError: str is not defined at /home/itemir/.signalk/node_modules/pico2signalk/index.js:86:14 at Array.forEach (<anonymous>) at Socket.<anonymous> (/home/itemir/.signalk/node_modules/pico2signalk/index.js:85:33) at Socket.emit (node:events:518:28) at UDP.onMessage [as onmessage] (node:dgram:988:8)
Jun 14 09:52:23 2025-06-14T16:52:23.641Z pico2signalk 0000000000ffb002817896008fff0001684da981ff0101684d46d7ff0201fffffc16ff030100018f1cff040100000009ff050100006610ff0901610fff1aff0a01fffffc16ff0b0100000550ff0c0100000000ff0d0100000000ff0e01000000b1ff0f010000ffffff1001000000cdff11010000001dff120100000000ff130103e8044cff140102cf02cfff150100b50110ff160103e8060eff2432
Jun 14 09:52:23 2025-06-14T16:52:23.641Z pico2signalk Length: 312
Jun 14 09:52:23 ReferenceError: str is not defined at /home/itemir/.signalk/node_modules/pico2signalk/index.js:86:14 at Array.forEach (<anonymous>) at Socket.<anonymous> (/home/itemir/.signalk/node_modules/pico2signalk/index.js:85:33) at Socket.emit (node:events:518:28) at UDP.onMessage [as onmessage] (node:dgram:988:8)
Jun 14 09:52:24 2025-06-14T16:52:24.741Z pico2signalk 0000000000ffb002817896008fff0001684da981ff0101684d4711ff0201fffffc16ff030100018f1cff040100000009ff050100006616ff0901610fff1aff0a01fffffc16ff0b0100000520ff0c0100000000ff0d0100000000ff0e01000000b1ff0f010000ffffff1001000000cdff11010000001dff120100000000ff130103e8044cff140102cf02cfff150100b50110ff160103e8060eff881c
Jun 14 09:52:24 2025-06-14T16:52:24.742Z pico2signalk Length: 312
Jun 14 09:52:24 ReferenceError: str is not defined at /home/itemir/.signalk/node_modules/pico2signalk/index.js:86:14 at Array.forEach (<anonymous>) at Socket.<anonymous> (/home/itemir/.signalk/node_modules/pico2signalk/index.js:85:33) at Socket.emit (node:events:518:28) at UDP.onMessage [as onmessage] (node:dgram:988:8)
Jun 14 09:52:25 2025-06-14T16:52:25.741Z pico2signalk 0000000000ffb002817896008fff0001684da983ff0101684d4713ff0201fffffc16ff030100018f1cff040100000009ff050100006616ff0901610fff1aff0a01fffffc16ff0b01000004ffff0c0100000000ff0d0100000000ff0e01000000b1ff0f010000ffffff1001000000ccff11010000001dff120100000000ff130103e8044cff140102cf02cfff150100b50110ff160103e8060efff770
Jun 14 09:52:25 2025-06-14T16:52:25.742Z pico2signalk Length: 312
Jun 14 09:52:25 ReferenceError: str is not defined at /home/itemir/.signalk/node_modules/pico2signalk/index.js:86:14 at Array.forEach (<anonymous>) at Socket.<anonymous> (/home/itemir/.signalk/node_modules/pico2signalk/index.js:85:33) at Socket.emit (node:events:518:28) at UDP.onMessage [as onmessage] (node:dgram:988:8)
```

Thoughts?

**Comment by htool** [comment]
First of all: the timeoout approach sounds promising. pico.py doesn't use that port, so I miss the logic on why there's an error as if the port is already in use. It remains confusing to me what's happening there.

Data seems to come in, but something (obviously) is off with the undefined string on line 86.

It's very difficult to debug a problem I don't see/have remote.

Can you uncomment some of the debug lines around that area and rerun?

**Comment by itemir** [comment]
It is funny, error is coming from the enabled debug message, `str` is not a valid JS function. Replacing it with `JSON.stringify` solves the error and plugin starts working again. Root-cause of the issue  is the race condition that is preventing the socket binding, with a delayed start (above fix), it started working again.

```
app.debug("sensorList[" + JSON.stringify(item) + "]: " + sensorList[item]["name"])
```

**Comment by GITnonameismyname** [comment]
> It is funny, error is coming from the enabled debug message, `str` is not a valid JS function. Replacing it with `JSON.stringify` solves the error and plugin starts working again. Root-cause of the issue is the race condition that is preventing the socket binding, with a delayed start (above fix), it started working again.
> 
> ```
> app.debug("sensorList[" + JSON.stringify(item) + "]: " + sensorList[item]["name"])
> ```

Hello, thx for your efforts. Can u explain for a beginner how to implement your fix in the code?
I did not understand where to put it or what to replace.
Many Thx


Got t:

in the file /data/conf/signalk/node_modules/pico2signalk/index.js

just replace

    socket.bind(port, function() {
      socket.setBroadcast(true);
      const address = socket.address()
      app.debug("Client using port " + address.port)
    })

with

    // Do a delayed start to prevent address in use error
    setTimeout (function () {
      app.debug('Binding to port');
      socket.bind(port, function() {
        socket.setBroadcast(true);
        const address = socket.address()
        app.debug("Client using port " + address.port)
      })
    }, 5000);

**Comment by htool** [comment]
Just pushed the delay. Hope that fixes it for everyone.
